### ISSUE TITLE
String Set data type not supported.

### ISSUE THREAD

**Issue by ishangupta094** [AmitPhulera/sails-dynamodb-v1#10]
Sails 1.0 Model does not support "array" type for an attribute, instead it asks us to configure it as 
`{ type: 'json', columnType: 'array' }`

When querying the database after configuring it so, the particular attribute fails to parse it from the way AWS Dynamo stores it internally.

**Comment by AmitPhulera** [comment]
Can you please provide and example on how to reproduce this behavior?

I am assuming that this situation might have occured while querying a table that already had data and schema for it is written after wards.  Can you verify that the attribute was of type list and not string set in DynamoDB console?

DynamoDB can have StringSet, NumberSet or List data types which are same as array. So if in schema you have written columnType as array and in DynamoDB the field was actually a stringset or numberset, this will raise exceptions.

**Comment by ishangupta094** [comment]
Sorry forgot to respond earlier.

I believe I had not configured it correctly.
