### ISSUE TITLE
Unhandled Exception thrown when doing an update query without  Range key.

### ISSUE THREAD

**Issue by saapra** [AmitPhulera/sails-dynamodb-v1#6]
The adapter is unable to perform "update" operations without "range" key. 

Error in 
sails-dynamodb-v1/index.js line 334 update function
code
```
 let Key = and.reduce((prev, curr) => ({ ...prev, ...curr }), {});
```

Here the value of "and" is undefined causing error.

**Comment by AmitPhulera** [comment]
Fixed in #8
