### ISSUE TITLE
Unhandled Exception 

### ISSUE THREAD

**Issue by ishangupta094** [AmitPhulera/sails-dynamodb-v1#9]
https://github.com/AmitPhulera/sails-dynamodb-v1/blob/20fa70d1bc72f912962796ed9c69278a45e435d2/utils/app.util.js#L464

If the attribute is not specified in the Model, and there is data present in Dynamo, this throws an Error.

Example:
My Model does not have an attribute "email" present. But the dynamo table has an entry with "email" as its key, your adapter throws an error. 

This happens because it can't normalise the data as it's datatype is unknown to it.

**Comment by AmitPhulera** [comment]
I guess this should be the default behavior. Schema is basically a class for your data and adding extra properties in data and not updating it in the schema does not makes sense.
Can you provide a usecase where it would be super important?

**Comment by AmitPhulera** [comment]
Fixed in #11
